[package]
name = "marksheet-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
marksheet-model = { path = "../marksheet-model" }
serde_json.workspace = true
time.workspace = true

[lints]
workspace = true
