[package]
name = "marksheet-calc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
marksheet-model = { path = "../marksheet-model" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
marksheet-syntax = { path = "../marksheet-syntax" }

[lints]
workspace = true
